"use client";
import { MonitorSmartphone } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { createBrowserSupabase } from "@/lib/supabase/browser";

export function DeviceActivation() {
  const router = useRouter(); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const activate = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(""); const supabase = createBrowserSupabase(); if (!supabase) { setError("Supabase 환경변수가 필요해요."); setLoading(false); return; } let { data } = await supabase.auth.getSession(); if (!data.session) { const result = await supabase.auth.signInAnonymously(); data = { session: result.data.session }; } if (!data.session) { setError("기기 세션을 만들 수 없어요."); setLoading(false); return; } const response = await fetch("/api/device/activate", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${data.session.access_token}` }, body: JSON.stringify({ code }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setError(body.error ?? "코드를 확인해 주세요."); return; } localStorage.setItem("studio-device-id", body.deviceId); localStorage.setItem("studio-device-type", body.deviceType); router.replace(body.deviceType === "staff_terminal" ? "/staff" : "/kiosk"); };
  return <main style={{ minHeight: "100dvh", display: "grid", placeItems: "center", padding: 24 }}><form className="card" style={{ width: "min(100%, 440px)", padding: 32 }} onSubmit={activate}><div style={{ width: 64, height: 64, borderRadius: 20, display: "grid", placeItems: "center", background: "var(--brand-weak)", color: "var(--brand)", marginBottom: 24 }}><MonitorSmartphone/></div><h1 className="title-lg">기기를 매장에 연결할게요</h1><p className="body muted">서비스 운영자가 발급한 일회용 코드를 입력해 주세요.</p><label style={{ display: "block", margin: "26px 0 14px" }}><span className="field-label">활성화 코드</span><input className="field" style={{ textTransform: "uppercase", letterSpacing: ".12em", fontSize: 22, textAlign: "center" }} value={code} maxLength={12} onChange={(e) => setCode(e.target.value.replace(/[^a-zA-Z0-9]/g, "").toUpperCase())}/></label>{error && <p className="error-copy">{error}</p>}<button className="btn btn-primary btn-block" disabled={code.length < 6 || loading}>{loading ? "연결 중..." : "기기 연결"}</button></form></main>;
}
