"use client";
import { Check, ChevronDown, Eye, RotateCcw, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { defaultCatalog } from "@/lib/catalog/defaults";
import type { Catalog } from "@/lib/catalog/schema";
import { formatWon } from "@/lib/catalog/calculate";
import styles from "./staff.module.css";

export function CatalogEditor() {
  const [draft, setDraft] = useState<Catalog>(() => structuredClone(defaultCatalog));
  const [openCategory, setOpenCategory] = useState(defaultCatalog.categories[0].id);
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; fetch("/api/staff/catalog", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!active) return; if (response.ok) { setDraft(body); setOpenCategory(body.categories[0]?.id ?? ""); } else setMessage(body.error ?? "운영 카탈로그를 불러오지 못했어요."); }).catch(() => { if (active) setMessage("운영 카탈로그를 불러오지 못했어요."); }); return () => { active = false; }; }, []);
  const products = useMemo(() => draft.products.filter((item) => item.categoryId === openCategory), [draft.products, openCategory]);
  const updatePrice = (id: string, value: string) => setDraft((catalog) => ({ ...catalog, products: catalog.products.map((product) => product.id === id ? { ...product, price: { amount: value === "" ? null : Math.max(0, Number(value)), label: value === "" ? "가격 상담" : undefined } } : product) }));
  const preview = async () => { setMessage(""); const response = await fetch("/api/staff/catalog/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); setMessage(response.ok ? "키오스크에 표시할 상품 설정을 확인했어요." : (await response.json()).error ?? "설정을 확인해 주세요."); };
  const publish = async () => { setSaving(true); setMessage(""); const response = await fetch("/api/staff/catalog/publish", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(draft) }); const body = await response.json(); setSaving(false); if (!response.ok) { setMessage(body.error ?? "운영 화면에 적용하지 못했어요."); return; } setDraft(body); setMessage(`카탈로그 v${body.version}을 운영 화면에 적용했어요.`); };
  const reset = () => { setDraft(structuredClone(defaultCatalog)); setMessage("작성 중 변경을 기본 템플릿으로 되돌렸어요."); };
  return <><header className="admin-header"><div><h1 className="title-lg">상품 관리</h1><p className="muted body">작성 중 설정을 미리 확인한 후 키오스크에 적용해요.</p></div><div className={styles.toolbar}><button className="btn btn-secondary" onClick={reset}><RotateCcw size={17}/>작성본 초기화</button><button className="btn btn-secondary" onClick={preview}><Eye size={17}/>미리보기 검증</button><button className="btn btn-primary" disabled={saving} onClick={publish}><Save size={17}/>{saving ? "적용 중..." : "운영 화면에 적용"}</button></div></header>{message && <div className="card" style={{ padding: 14, marginBottom: 18, color: message.includes("못") || message.includes("권한") ? "var(--danger)" : "var(--success)" }}><Check size={17}/> {message}</div>}<div style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 18 }}><nav className="table-card" style={{ padding: 10, alignSelf: "start" }}>{draft.categories.map((category) => <button key={category.id} className={`sidebar-link ${openCategory === category.id ? "active" : ""}`} style={{ width: "100%" }} onClick={() => setOpenCategory(category.id)}>{category.name}</button>)}</nav><section><div className="table-card">{products.map((product) => <div className={styles.catalogRow} key={product.id}><span><strong>{product.name}</strong><small className="tertiary" style={{ display: "block", marginTop: 4 }}>{product.tag}</small></span><label className="caption"><input type="checkbox" checked={product.active} onChange={(e) => setDraft((catalog) => ({ ...catalog, products: catalog.products.map((item) => item.id === product.id ? { ...item, active: e.target.checked } : item) }))}/> 판매</label><label><input aria-label={`${product.name} 가격`} className="field price" style={{ minHeight: 44, textAlign: "right" }} inputMode="numeric" value={product.price.amount ?? ""} placeholder="가격 상담" onChange={(e) => updatePrice(product.id, e.target.value.replace(/\D/g,""))}/></label><ChevronDown size={18}/></div>)}</div><div className="caption tertiary" style={{ marginTop: 12 }}>현재 작성본 v{draft.version} · 저장 전에는 고객 화면에 반영되지 않아요. 금액이 비어 있으면 {formatWon(null)}으로 표시돼요.</div></section></div></>;
}

